# 01 - Data Cleaning

## Objective

In this notebook, we will:

- Load the raw dataset
- Inspect the dataset structure
- Check data types
- Identify missing values
- Check duplicate records
- Identify invalid values
- Clean the dataset
- Save the cleaned dataset

In [1]:
import sys
from pathlib import Path
PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

In [2]:
import pandas as pd # pyright: ignore[reportMissingModuleSource]
import numpy as np # pyright: ignore[reportMissingImports]
from src.data_processing import load_data, clean_data

In [3]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
RAW_DATA_PATH = (
PROJECT_ROOT / "data" / "raw" / "WA_Fn-UseC_-Telco-Customer-Churn.csv"
)

In [5]:
df = load_data(RAW_DATA_PATH)

In [6]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [7]:
df.shape

(7043, 21)

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [9]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customerID,7043,7043,7590-VHVEG,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,7043,2,Male,3555,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SeniorCitizen,7043.0,NaN,NaN,NaN,0.162147,0.368612,0.0,0.0,0.0,0.0,1.0
Partner,7043,2,No,3641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dependents,7043,2,No,4933,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tenure,7043.0,NaN,NaN,NaN,32.371149,24.559481,0.0,9.0,29.0,55.0,72.0
PhoneService,7043,2,Yes,6361,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MultipleLines,7043,3,No,3390,NaN,NaN,NaN,NaN,NaN,NaN,NaN
InternetService,7043,3,Fiber optic,3096,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OnlineSecurity,7043,3,No,3498,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OnlineBackup,7043,3,No,3088,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DeviceProtection,7043,3,No,3095,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TechSupport,7043,3,No,3473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StreamingTV,7043,3,No,2810,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StreamingMovies,7043,3,No,2785,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Contract,7043,3,Month-to-month,3875,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaperlessBilling,7043,2,Yes,4171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaymentMethod,7043,4,Electronic check,2365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MonthlyCharges,7043.0,NaN,NaN,NaN,64.761692,30.090047,18.25,35.5,70.35,89.85,118.75
TotalCharges,7043,6531,20.2,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Churn,7043,2,No,5174,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [86]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [87]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [88]:
df.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [89]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [10]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors='coerce')

In [91]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
dtype: object

In [11]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [62]:
df["customerID"].nunique()

7043

In [63]:
len(df)

7043

In [93]:
categorical_columns = df.select_dtypes(
    include="object"
).columns

for column in categorical_columns:
    print(f"\n--- {column} ---")
    print(df[column].value_counts(dropna=False))

--- customerID ---
customerID
7590-VHVEG    1
5575-GNVDE    1
3668-QPYBK    1
7795-CFOCW    1
9237-HQITU    1
9305-CDSKC    1
1452-KIOVK    1
6713-OKOMC    1
7892-POOKP    1
6388-TABGU    1
9763-GRSKD    1
7469-LKBCI    1
8091-TTVAX    1
0280-XJGEX    1
5129-JLPIS    1
3655-SNQYZ    1
8191-XWSZG    1
9959-WOFKT    1
4190-MFLUW    1
4183-MYFRB    1
8779-QRDMV    1
1680-VDCWW    1
1066-JKSGK    1
3638-WEABW    1
6322-HRPFA    1
6865-JZNKO    1
6467-CHFZW    1
8665-UTDHZ    1
5248-YGIJN    1
8773-HHUOZ    1
3841-NFECX    1
4929-XIHVW    1
6827-IEAUQ    1
7310-EGVHZ    1
3413-BMNZE    1
6234-RAAPL    1
6047-YHPVI    1
6572-ADKRS    1
5380-WJKOV    1
8168-UQWWF    1
8865-TNMNX    1
9489-DEDVP    1
9867-JCZSP    1
4671-VJLCL    1
4080-IIARD    1
3714-NTNFO    1
5948-UJZLF    1
7760-OYPDY    1
7639-LIAYI    1
2954-PIBKO    1
8012-SOUDQ    1
9420-LOJKX    1
6575-SUVOI    1
7495-OOKFY    1
4667-QONEA    1
1658-BYGOY    1
8769-KKTPH    1
5067-XJQFU    1
3957-SQXML    1
5954-BDFSG    1
0434-CSFON    1
1215-FIGMP    1
0526-SXDJP    1
0557-ASKVU    1
5698-BQJOH    1
5122-CYFXA    1
8627-ZYGSZ    1
3410-YOQBQ    1
3170-NMYVV    1
7410-OIEDU    1
2273-QCKXA    1
0731-EBJQB    1
1891-QRQSA    1
8028-PNXHQ    1
5630-AHZIL    1
2673-CXQEU    1
6416-JNVRK    1
5590-ZSKRV    1
0191-ZHSKZ    1
3887-PBQAO    1
5919-TMRGD    1
8108-UXRQN    1
9191-MYQKX    1
9919-YLNNG    1
0318-ZOPWS    1
4445-ZJNMU    1
4808-YNLEU    1
1862-QRWPE    1
2796-NNUFI    1
3016-KSVCP    1
4767-HZZHQ    1
2424-WVHPL    1
7233-PAHHL    1
6067-NGCEU    1
9848-JQJTX    1
8637-XJIVR    1
9803-FTJCG    1
0278-YXOOG    1
3212-KXOCR    1
4598-XLKNJ    1
6380-ARCEH    1
3679-XASPY    1
7123-WQUHX    1
5386-THSLQ    1
3192-NQECA    1
6180-YBIQI    1
6728-DKUCO    1
9750-BOOHV    1
8597-CWYHH    1
2848-YXSMW    1
0486-HECZI    1
4549-ZDQYY    1
5712-AHQNN    1
4846-WHAFZ    1
5256-SKJGO    1
3071-VBYPO    1
9560-BBZXK    1
5299-RULOA    1
8402-OOOHJ    1
9445-ZUEQE    1
1091-SOZGA    1
2928-HLDBA    1
0404-SWRVG    1
6497-TILVL    1
7219-TLZHO    1
4622-YNKIJ    1
4412-YLTKF    1
6734-PSBAW    1
3930-ZGWVE    1
2639-UGMAZ    1
2876-GZYZC    1
6207-WIOLX    1
8587-XYZSF    1
3091-FYHKI    1
2372-HWUHI    1
7799-LGRDP    1
7850-VWJUU    1
3774-VBNXY    1
6217-KDYWC    1
0390-DCFDQ    1
3146-MSEGF    1
4080-OGPJL    1
1095-WGNGG    1
2636-SJDOU    1
1131-QQZEB    1
5716-EZXZN    1
6837-BJYDQ    1
2135-RXIHG    1
6440-DKQGE    1
3466-BYAVD    1
3780-YVMFA    1
3874-EQOEP    1
1679-JRFBR    1
9073-ZZIAY    1
3077-RSNTJ    1
6551-GNYDG    1
9167-APMXZ    1
2749-CTKAJ    1
6371-NZYEG    1
7554-NEWDD    1
8992-VONJD    1
0867-MKZVY    1
4482-EWFMI    1
4648-YPBTM    1
2907-ILJBN    1
6345-FZOQH    1
3376-BMGFE    1
5997-OPVFA    1
3445-HXXGF    1
1159-WFSGR    1
7654-YWJUF    1
1875-QIVME    1
6727-IOTLZ    1
0691-JVSYA    1
5918-VUKWP    1
1744-JHKYS    1
2656-FMOKZ    1
2070-FNEXE    1
5947-SGKCL    1
3712-PKXZA    1
6317-YPKDH    1
6582-OIVSP    1
9367-WXLCH    1
5524-KHNJP    1
1918-ZBFQJ    1
1024-GUALD    1
4827-USJHP    1
8167-GJLRN    1
0956-SYCWG    1
8017-UVSZU    1
7100-FQPRV    1
2472-OVKUP    1
2984-RGEYA    1
9680-NIAUV    1
2146-EGVDT    1
2604-IJPDU    1
9178-JHUVJ    1
6168-YBYNP    1
7255-SSFBC    1
3645-DEYGF    1
9323-HGFWY    1
8544-GOQSH    1
3363-DTIVD    1
7018-WBJNK    1
9142-KZXOP    1
7674-YTAFD    1
6348-SNFUS    1
1285-OKIPP    1
7825-ECJRF    1
1347-KTTTA    1
7841-TZDMQ    1
4195-NZGTA    1
7157-SMCFK    1
4709-LKHYG    1
2504-DSHIH    1
0699-NDKJM    1
9286-BHDQG    1
0230-WEQUW    1
2040-LDIWQ    1
6496-JDSSB    1
9408-SSNVZ    1
4443-EMBNA    1
6469-MRVET    1
0742-MOABM    1
5961-VUSRV    1
6778-JFCMK    1
6341-JVQGF    1
2232-DMLXU    1
4811-JBUVU    1
0945-TSONX    1
2651-ZCBXV    1
3316-UWXUY    1
8937-RDTHP    1
7083-MIOPC    1
1984-GPTEH    1
1251-KRREG    1
0621-JFHOL    1
9903-LYSAB    1
0094-OIFMO    1
9227-UAQFT    1
7301-ABVAD    1
6614-FHDBO    1
7576-ASEJU    1
9058-HRZSV    1
4522-AKYLR    1
0221-WMXNQ    1
0303-UNCIP    1
9947-OTFQU    1
0322-YINQP    1
0959-WHOKV    1
4075-JFPGR    1
4629-NRXKX    1
9514-JDSKI    1
3282-ZISZV    1
3675-YDUPJ    1
4111-BNXIF    1
7017-VFHAY    1
6655-LHBYW    1
4959-JOSRX    1
5046-NUHWD    1
7273-TEFQD    1
3606-TWKGI    1
7529-ZDFXI    1
7605-BDWDC    1
1950-KSVVJ    1
0123-CRBRT    1
6292-TOSSS    1
3197-ARFOY    1
6323-AYBRX    1
7014-ZZXAW    1
4385-GZQXV    1
7633-MVPUY    1
6366-ZGQGL    1
4716-HHKQH    1
5940-AHUHD    1
6432-TWQLB    1
4484-GLZOU    1
3179-GBRWV    1
8645-KWHJO    1
4130-MZLCC    1
0314-TKOSI    1
8229-MYEJZ    1
2080-SRCDE    1
9577-WJVCQ    1
9512-UIBFX    1
6202-DYYFX    1
3808-HFKDE    1
5583-SXDAG    1
3488-PGMQJ    1
3580-REOAC    1
7534-BFESC    1
3727-OWVYD    1
2294-SALNE    1
4847-TAJYI    1
1563-IWQEX    1
8203-XJZRC    1
6556-DBKZF    1
6851-WEFYX    1
2985-JUUBZ    1
6390-DSAZX    1
0895-LMRSF    1
8098-LLAZX    1
8266-VBFQL    1
8181-YHCMF    1
2240-HSJQD    1
1248-DYXUB    1
0265-EDXBD    1
4115-BNPJY    1
3167-SNQPL    1
4091-TVOCN    1
1098-TDVUQ    1
7277-OZCGZ    1
1557-EMYVT    1
2799-ARNLO    1
7563-BIUPC    1
5027-YOCXN    1
3973-SKMLN    1
2321-OMBXY    1
2840-XANRC    1
6745-JEFZB    1
5020-ZSTTY    1
9880-TDQAC    1
8705-WZCYL    1
7102-JJVTX    1
8626-PTQGE    1
4983-CLMLV    1
5701-YVSVF    1
5804-LEPIM    1
5697-GOMBF    1
2739-CACDQ    1
9385-EHGDO    1
9498-FIMXL    1
2379-GYFLQ    1
0122-OAHPZ    1
2868-SNELZ    1
4322-RCYMT    1
6680-NENYN    1
2088-IEBAU    1
7982-VCELR    1
1343-EHPYB    1
6035-BXTTY    1
6885-PKOAM    1
7520-HQWJU    1
9639-BUJXT    1
5924-SNGKP    1
0021-IKXGC    1
2034-GDRCN    1
8966-SNIZF    1
6243-OZGFH    1
4654-DLAMQ    1
0513-RBGPE    1
5160-UXJED    1
4115-NZRKS    1
0219-YTZUE    1
0623-IIHUG    1
4572-DVCGN    1
3351-NGXYI    1
8984-EYLLL    1
9057-MSWCO    1
9833-TGFHX    1
9294-TDIPC    1
5229-DTFYB    1
0104-PPXDV    1
5176-LMJXE    1
3583-KRKMD    1
1010-DIAUQ    1
9069-LGEUL    1
7302-ZHMHP    1
9571-EDEBV    1
3520-FJGCV    1
6563-VRERX    1
0259-GBZSH    1
6122-EFVKN    1
2805-EDJPQ    1
6862-CQUMB    1
7156-MXBJE    1
6158-HDPXZ    1
9601-BRXPO    1
2863-IMQDR    1
5686-CMAWK    1
5651-CRHKQ    1
6905-NIQIN    1
8204-YJCLA    1
5167-ZFFMM    1
6583-SZVGP    1
4895-TMWIR    1
0533-BNWKF    1
1708-PBBOA    1
8782-LKFPK    1
5522-JBWMO    1
3597-MVHJT    1
9774-NRNAU    1
0224-RLWWD    1
9967-ATRFS    1
3951-NJCVI    1
2977-CEBSX    1
0177-PXBAT    1
6599-CEBNN    1
2519-ERQOJ    1
5876-QMYLD    1
2277-AXSDC    1
9442-JTWDL    1
0979-PHULV    1
3067-SVMTC    1
5495-GPSRW    1
7606-BPHHN    1
4742-DRORA    1
0111-KLBQG    1
4800-VHZKI    1
7989-CHGTL    1
0334-GDDSO    1
4163-NCJAK    1
5233-AOZUF    1
5973-EJGDP    1
1996-DBMUS    1
7916-VCCPB    1
4686-GEFRM    1
5249-QYHEX    1
0578-SKVMF    1
5564-NEMQO    1
2233-FAGXV    1
5605-IYGFG    1
7663-ZTEGJ    1
3935-TBRZZ    1
8111-BKVDS    1
2055-SIFSS    1
2806-MLNTI    1
8734-DKSTZ    1
4360-PNRQB    1
6152-ONASV    1
9063-ZGTUY    1
7781-HVGMK    1
2181-UAESM    1
2957-LOLHO    1
6048-NJXHX    1
2320-SLKMB    1
4980-URKXC    1
4376-KFVRS    1
5886-VLQVU    1
3577-AMVUX    1
0771-WLCLA    1
5628-RKIFK    1
0206-TBWLC    1
2937-FTHUR    1
1910-FMXJM    1
7752-XUSCI    1
4110-PFEUZ    1
0732-OCQOC    1
5168-MSWXT    1
1090-ESELR    1
8592-PLTMQ    1
5760-WRAHC    1
8847-GEOOQ    1
0256-LTHVJ    1
4785-FCIFB    1
8313-NDOIA    1
5149-CUZUJ    1
0942-KOWSM    1
4237-CLSMM    1
1452-VOQCH    1
4719-UMSIY    1
6614-VBEGU    1
0880-TKATG    1
3811-VBYBZ    1
1480-BKXGA    1
2996-XAUVF    1
9076-AXYIK    1
5968-XQIVE    1
8896-RAZCR    1
4640-UHDOS    1
4933-IKULF    1
3583-EKAPL    1
1304-BCCFO    1
4104-PVRPS    1
9399-APLBT    1
2359-KMGLI    1
3780-DDGSE    1
4431-EDMIQ    1
0306-JAELE    1
6227-HWPWX    1
0486-LGCCH    1
0447-BEMNG    1
4612-SSVHJ    1
5168-MQQCA    1
5949-XIKAE    1
7971-HLVXI    1
9094-AZPHK    1
3649-JPUGY    1
4472-LVYGI    1
8372-JUXUI    1
3552-CTCYF    1
6778-YSNIH    1
0388-EOPEX    1
5756-OZRIO    1
6579-JPICP    1
8205-OTCHB    1
4134-BSXLX    1
0505-SPOOW    1
6235-VDHOM    1
7783-YKGDV    1
4374-YMUSQ    1
4513-CXYIX    1
3957-HHLMR    1
7803-XOCCZ    1
5736-YEJAX    1
5609-CEBID    1
8981-FJGLA    1
7218-HKQFK    1
4636-QRJKY    1
1135-LMECX    1
4332-MUOEZ    1
8535-SFUTN    1
5956-VKDTT    1
8677-HDZEE    1
2475-MROZF    1
9412-GHEEC    1
3482-ABPKK    1
6705-LXORM    1
0257-ZESQC    1
7531-GQHME    1
5174-ITUMV    1
4109-CYRBD    1
0913-XWSCN    1
6825-UYPFK    1
8397-MVTAZ    1
0750-EBAIU    1
8606-CIQUL    1
3571-DPYUH    1
7601-GNDYK    1
0356-OBMAC    1
8067-NIOYM    1
1403-GYAFU    1
4234-XTNEA    1
1297-VQDRP    1
9282-IZGQK    1
5348-CAGXB    1
0621-HJWXJ    1
5844-QVTAT    1
8905-IAZPF    1
5394-MEITZ    1
6859-QNXIQ    1
2782-LFZVW    1
2866-IKBTM    1
1342-JPNKI    1
2817-NTQDO    1
7129-AZJDE    1
6986-IJDHX    1
2560-PPCHE    1
4676-MQUEA    1
8138-EALND    1
3580-HYCSP    1
1352-HNSAW    1
2075-PUEPR    1
1982-FEBTD    1
5301-GAUUY    1
5791-KAJFD    1
2654-VBVPB    1
1154-HYWWO    1
2501-XWWTZ    1
3716-UVSPD    1
6815-ABQFQ    1
7343-EOBEU    1
3701-SFMUH    1
6103-LIANB    1
7319-VENRZ    1
5846-NEQVZ    1
6967-QIQRV    1
5781-RFZRP    1
0939-YAPAF    1
0308-IVGOK    1
7293-LSCDV    1
7025-WCBNE    1
5756-JYOJT    1
4710-FDUIZ    1
6030-REHUX    1
9548-LIGTA    1
5150-LJNSR    1
8270-RKSAP    1
6522-YRBXD    1
2640-LYMOV    1
1218-VKFPE    1
3627-FHKBK    1
2865-TCHJW    1
1423-BMPBQ    1
2393-DIVAI    1
5192-EBGOV    1
4568-KNYWR    1
8752-IMQOS    1
0742-LAFQK    1
0795-LAFGP    1
0619-OLYUR    1
5512-IDZEI    1
0459-SPZHJ    1
0215-BQKGS    1
9244-ZVAPM    1
0719-SYFRB    1
8208-EUMTE    1
5172-MIGPM    1
1710-RCXUS    1
0374-FIUCA    1
5839-SUYVZ    1
5173-ZXXXL    1
1096-ADRUX    1
2001-MCUUW    1
2731-GJRDG    1
4723-BEGSG    1
6516-NKQBO    1
8672-OAUPW    1
8207-DMRVL    1
3419-SNJJD    1
6543-CPZMK    1
4765-OXPPD    1
2804-ETQDK    1
6689-VRRTK    1
7138-GIRSH    1
9396-ZSFLL    1
6464-KEXXH    1
7134-MJPDY    1
5240-CAOYT    1
4059-IIEBK    1
4881-JVQOD    1
0516-UXRMT    1
4851-BQDNX    1
5148-HKFIR    1
1009-IRMNA    1
3003-CMDUU    1
5016-IBERQ    1
6797-UCJHZ    1
2469-DTSGX    1
4554-YGZIH    1
5099-BAILX    1
9931-KGHOA    1
1775-KWJKQ    1
7665-VIGUD    1
9411-TPQQV    1
7207-RMRDB    1
7954-MLBUN    1
2077-DDHJK    1
4913-EHYUI    1
0195-IESCP    1
9574-BOSMD    1
4580-TMHJU    1
0970-ETWGE    1
4908-XAXAY    1
8404-VLQFB    1
1626-ERCMM    1
0887-HJGAR    1
2391-IPLOP    1
5644-PDMZC    1
3509-GWQGF    1
9576-ANLXO    1
2024-BASKD    1
5845-BZZIB    1
1140-UKVZG    1
4160-AMJTL    1
5183-SNMJQ    1
8100-PNJMH    1
7838-LAZFO    1
4464-JCOLN    1
2085-JVGAD    1
5650-VDUDS    1
8095-WANWK    1
3030-ZKIWL    1
9565-FLVCG    1
8755-OGKNA    1
2800-VEQXM    1
7538-GWHML    1
5533-RJFTJ    1
3859-CVCET    1
0214-JHPFW    1
5642-MHDQT    1
3088-FVYWK    1
3276-HDUEG    1
9092-GDZKO    1
0823-HSCDJ    1
3729-OWRVL    1
2324-AALNO    1
0822-GAVAP    1
5760-IFJOZ    1
2826-UWHIS    1
1448-PWKYE    1
7501-IWUNG    1
4957-TREIR    1
7251-LJBQN    1
8040-MNRTF    1
1536-HBSWP    1
5313-FPXWG    1
0067-DKWBL    1
0946-FKYTX    1
5076-YVXCM    1
8262-COGGB    1
6663-JOCQO    1
9620-QJREV    1
2276-YDAVZ    1
2682-KEVRP    1
2480-JZOSN    1
0078-XZMHT    1
5896-NPFWW    1
9978-HYCIN    1
8338-QIUNR    1
1525-LNLOJ    1
9450-TRJUU    1
1766-GKNMI    1
6942-LBFDP    1
1456-TWCGB    1
7133-VBDCG    1
7596-ZYWBB    1
8329-UTMVM    1
3014-WJKSM    1
3347-YJZZE    1
1029-QFBEN    1
7929-DMBCV    1
9661-JALZV    1
5433-KYGHE    1
4312-KFRXN    1
5575-TPIZQ    1
0114-IGABW    1
9944-AEXBM    1
1853-ARAAQ    1
6952-OMNWB    1
4697-LUPSU    1
8434-VGEQQ    1
4952-YSOGZ    1
1589-AGTLK    1
5244-IRFIH    1
6549-YMFAW    1
4950-HKQTE    1
6786-OBWQR    1
2684-EIWEO    1
2753-JMMCV    1
6439-GTPCA    1
6621-YOBKI    1
1216-JWVUX    1
7564-GHCVB    1
1173-NOEYG    1
7595-EHCDL    1
6647-ZEDXT    1
2521-NPUZR    1
1307-TVUFB    1
7503-MIOGA    1
4381-MHQDC    1
6923-JHPMP    1
5138-WVKYJ    1
4018-PPNDW    1
1635-FJFCC    1
2499-AJYUA    1
6919-ELBGL    1
3966-HRMZA    1
6425-JWTDV    1
8405-IGQFX    1
8224-IVVPA    1
9477-LGWQI    1
1410-RSCMR    1
3115-CZMZD    1
0139-IVFJG    1
6683-VLCTZ    1
5730-DBDSI    1
0030-FNXPP    1
2189-WWOEW    1
5684-FJVYR    1
4013-GUXND    1
1894-IGFSG    1
7379-POKDZ    1
1266-NZYUI    1
7969-FFOWG    1
4718-DHSMV    1
5175-WLYXL    1
7817-OMJNA    1
8728-SKJLR    1
3137-NYQQI    1
7706-DZNKK    1
0236-HFWSV    1
3900-AQPHZ    1
5842-POCOP    1
2037-XJFUP    1
8823-RLPWL    1
9505-SQFSW    1
7314-OXENN    1
3758-CKOQL    1
0322-CHQRU    1
5676-CFLYY    1
7521-AFHAB    1
0285-INHLN    1
4678-DVQEO    1
5125-CNDSP    1
0691-IFBQW    1
4992-LTJNE    1
2202-OUTMO    1
0810-BDHAW    1
0229-LFJAF    1
7131-ZQZNK    1
3442-ZHHCC    1
5726-CVNYA    1
9871-ELEYA    1
4257-GAESD    1
5173-WXOQV    1
2040-OBMLJ    1
6286-ZHAOK    1
3807-XHCJH    1
3009-JWMPU    1
5671-RQRLP    1
1450-GALXR    1
8859-AXJZP    1
3174-AKMAS    1
3138-BKYAV    1
9926-PJHDQ    1
7382-DFJTU    1
2798-NYLMZ    1
4289-DTDKW    1
1820-TQVEV    1
2239-JALAW    1
4853-RULSV    1
8098-TDCBU    1
3551-GAEGL    1
4785-NKHCX    1
3196-NVXLZ    1
6275-YDUVO    1
0036-IHMOT    1
0115-TFERT    1
4178-EGMON    1
4220-TINQT    1
5318-YKDPV    1
7975-TZMLR    1
0295-QVKPB    1
4335-BSMJS    1
2311-QYMUQ    1
3643-AHCFP    1
9146-JRIOX    1
3104-OWCGK    1
5337-IIWKZ    1
9101-BWFSS    1
9650-VBUOG    1
3487-EARAT    1
2672-TGEFF    1
9231-ZJYAM    1
4250-WAROZ    1
8184-WMOFI    1
6982-SSHFK    1
6092-QZVPP    1
4625-LAMOB    1
0727-BMPLR    1
0392-BZIUW    1
1038-ZAGBI    1
6549-NNDYT    1
3027-ZTDHO    1
0422-OHQHQ    1
6916-HIJSE    1
2316-ESMLS    1
9778-OGKQZ    1
7408-OFWXJ    1
6007-TCTST    1
2252-NKNSI    1
8713-IGZSO    1
7905-TVXTA    1
7695-PKLCZ    1
2382-BCKQJ    1
8374-UULRV    1
2207-NHRJK    1
3224-DFQNQ    1
5275-PMFUT    1
4795-UXVCJ    1
9777-IQHWP    1
0947-MUGVO    1
9944-HKVVB    1
4124-MMETB    1
3671-SHRSP    1
0979-MOZQI    1
2732-ISEZX    1
3313-QKNKB    1
0323-XWWTN    1
1937-OTUKY    1
1573-LGXBA    1
1764-VUUMT    1
5073-WXOYN    1
4713-ZBURT    1
3050-GBUSH    1
0207-MDKNV    1
7876-AEHIG    1
7945-HLKEA    1
9342-VNIMQ    1
9851-KIELU    1
3523-BRGUW    1
3908-BLSYF    1
3199-NPKCN    1
5170-PTRKA    1
4661-NJEUX    1
2123-AGEEN    1
1258-YMZNM    1
0048-LUMLS    1
7549-MYGPK    1
5898-IGSLP    1
3804-RVTGV    1
6259-WJQLC    1
9227-LUNBG    1
7997-EASSD    1
0730-KOAVE    1
8975-SKGRX    1
0678-RLHVP    1
4315-MURBD    1
2267-FPIMA    1
1051-GEJLJ    1
9734-YWGEX    1
2719-BDAQO    1
5285-MVEHD    1
0379-DJQHR    1
0781-LKXBR    1
5543-QDCRY    1
0297-RBCSG    1
4694-PHWFW    1
0835-JKADZ    1
1907-UBQFC    1
7508-SMHXL    1
3865-YIOTT    1
5993-BQHEA    1
6024-RUGGH    1
6513-EECDB    1
3956-CJUST    1
4079-WWQQQ    1
6103-BOCOU    1
5149-TGWDZ    1
7471-WNSUF    1
8942-DBMHZ    1
4301-VVZKA    1
9199-PWQVC    1
4824-GUCBY    1
5393-HJZSM    1
7074-IEVOJ    1
9625-QSTYE    1
0862-PRCBS    1
8812-ZRHFP    1
5146-CBVOE    1
0454-OKRCT    1
5787-KXGIY    1
4750-ZRXIU    1
4198-VFOEA    1
6630-UJZMY    1
5709-LVOEQ    1
6400-BWQKW    1
2692-AQCPF    1
0347-UBKUZ    1
0835-DUUIQ    1
0811-GSDTP    1
7567-ECMCM    1
6115-ZTBFQ    1
6353-BRMMA    1
6680-WKXRZ    1
6231-WFGFH    1
9904-EHEVJ    1
7028-DVOIQ    1
6169-PPETC    1
4208-UFFGW    1
8584-KMVXD    1
8467-WYNSR    1
0851-DFJKB    1
5382-SOYZL    1
9448-REEVD    1
3261-CQXOL    1
8388-FYNPZ    1
4002-BQWPQ    1
5651-YLPRD    1
2826-DXLQO    1
4378-BZYFP    1
9489-UTFKA    1
4849-PYRLQ    1
9117-SHLZX    1
9889-TMAHG    1
4541-RMRLG    1
7764-BDPEE    1
3429-IFLEM    1
3158-MOERK    1
7294-TMAOP    1
5002-GCQFH    1
0556-FJEGU    1
8919-FYFQZ    1
0604-THJFP    1
2834-JRTUA    1
5875-YPQFJ    1
5879-SESNB    1
6646-QVXLR    1
6461-PPAXN    1
3318-ISQFQ    1
1106-HRLKZ    1
2483-XSSMZ    1
8603-IJWDN    1
8165-ZJRNM    1
9369-XFEHK    1
2604-XVDAM    1
3717-OFRTN    1
9046-JBFWA    1
3280-NMUVX    1
1206-EHBDD    1
8361-LBRDI    1
4883-KCPZJ    1
9108-EQPNQ    1
7277-KAMWT    1
3842-IYKUE    1
6641-XRPSU    1
1374-DMZUI    1
2545-LXYVJ    1
3234-VKACU    1
8357-EQXFO    1
1989-PRJHP    1
8120-JDCAM    1
8917-FAEMR    1
7047-YXDMZ    1
2858-EIMXH    1
9524-EGPJC    1
6993-OHLXR    1
8818-XYFCQ    1
6419-ZTTLE    1
0929-HYQEW    1
6614-YOLAC    1
7426-RHZGU    1
4065-JJAVA    1
4695-VADHF    1
3863-IUBJR    1
7649-SIJJF    1
9361-YNQWJ    1
3748-FVMZZ    1
9391-TTOYH    1
1452-XRSJV    1
3422-WJOYD    1
8242-SOQUO    1
7460-ITWWP    1
7147-AYBAA    1
7868-TMWMZ    1
4822-RVYBB    1
6732-FZUGP    1
8436-BJUMM    1
4184-TJFAN    1
8329-GWVPJ    1
1352-VHKAJ    1
4145-UQXUQ    1
2632-TACXW    1
8146-QQKZH    1
1767-CJKBA    1
6445-TNRXS    1
4581-LNWUM    1
4869-EPIUS    1
9948-YPTDG    1
1236-WFCDV    1
1915-OAKWD    1
7296-PIXQY    1
4883-QICIH    1
3354-OADJP    1
3524-WQDSG    1
0810-DHDBD    1
4026-SKKHW    1
2829-HYVZP    1
8329-IBCTI    1
1271-SJBGZ    1
3845-JHAMY    1
7013-PSXHK    1
5669-SRAIP    1
5981-ITEMU    1
3486-NPGST    1
6941-PMGEP    1
1624-WOIWJ    1
2074-GKOWZ    1
0376-YMCJC    1
6100-FJZDG    1
4829-ZLJTK    1
1730-VFMWO    1
7143-BQIBA    1
3800-LYTRK    1
0634-SZPQA    1
9646-NMHXE    1
7030-NJVDP    1
5536-RTPWK    1
8883-GRDWQ    1
6166-ILMNY    1
3097-NNSPB    1
7771-ZONAT    1
0655-RBDUG    1
2111-DWYHN    1
4194-WHFCB    1
4121-AGSIN    1
4361-BKAXE    1
9845-PEEKO    1
0455-XFASS    1
0301-KOBTQ    1
1751-NCDLI    1
4367-NUYAO    1
9878-TNQGW    1
9170-ARBTB    1
4441-NIHPT    1
8999-BOHSE    1
7241-AJHFS    1
7029-RPUAV    1
4546-FOKWR    1
9036-CSKBW    1
5832-TRLPB    1
8590-YFFQO    1
8659-IOOPU    1
1338-CECEE    1
7439-DKZTW    1
4646-QZXTF    1
4607-CHPCA    1
9742-XOKTS    1
6921-OZMFH    1
9578-FOMUK    1
4712-UYOOI    1
8824-RWFXJ    1
7722-CVFXN    1
8717-VCTXJ    1
7363-QTBIW    1
4159-NAAIX    1
0971-QIFJK    1
9397-TZSHA    1
3391-JSQEW    1
0343-QLUZP    1
9763-PDTKK    1
2176-LVPNX    1
7627-JKIAZ    1
3312-UUMZW    1
1271-UODNO    1
8461-EFQYM    1
6900-RBKER    1
6891-JPYFF    1
1459-QNFQT    1
1047-NNCBF    1
3696-XRIEN    1
4081-DYXAV    1
0074-HDKDG    1
8791-GFXLZ    1
8111-SLLHI    1
0927-LCSMG    1
9330-DHBFL    1
0098-BOWSO    1
3452-ABWRL    1
5859-HZYLF    1
8257-RZAHR    1
5293-WXJAK    1
3156-QLHBO    1
2208-NQBCT    1
1779-PWPMG    1
6621-NRZAK    1
0831-JNISG    1
0774-IFUVM    1
3082-WQRVY    1
9553-DLCLU    1
1641-BYBTK    1
2460-NGXBJ    1
2446-ZKVAF    1
0841-NULXI    1
3522-CDKHF    1
1430-SFQSA    1
0411-EZJZE    1
7851-WZEKY    1
8844-TONUD    1
8807-ARQET    1
8992-CEUEN    1
4320-QMLLA    1
8777-PVYGU    1
8292-ITGYJ    1
6870-ZWMNX    1
0621-CXBKL    1
5268-DSMNQ    1
5334-JLAXU    1
4086-YQSNZ    1
6242-MBHPK    1
5868-CZJDR    1
9359-UGBTK    1
0135-NMXAP    1
4782-OSFXZ    1
6479-OAUSD    1
7129-ACFOG    1
4189-NAKJS    1
5562-BETPV    1
1282-IHQAC    1
9127-FHJBZ    1
6270-OMFIW    1
1641-RQDAY    1
0107-WESLM    1
6994-ORCWG    1
1346-UFHAX    1
3992-YWPKO    1
2933-XEUJM    1
0125-LZQXK    1
5461-QKNTN    1
4835-YSJMR    1
8399-YNDCH    1
3164-YAXFY    1
0887-WBJVH    1
4660-IRIBM    1
5673-FSSMF    1
7670-ZBPOQ    1
8089-UZWLX    1
0080-OROZO    1
3916-NRPAP    1
6807-SIWJI    1
8221-HVAYI    1
1579-KLYDT    1
5232-NXPAY    1
8967-SZQAS    1
4468-KAZHE    1
0455-ENTCR    1
8944-AILEF    1
5542-NKVRU    1
7126-RBHSD    1
5370-IIVVL    1
6789-HJBWG    1
3927-NLNRY    1
9087-EYCPR    1
6791-YBNAK    1
6358-LYNGM    1
6077-BDPXA    1
0013-MHZWF    1
5494-HECPR    1
8268-YDIXR    1
9824-BEMCV    1
1373-ORVIZ    1
4291-SHSBH    1
6980-IMXXE    1
9866-QEVEE    1
9897-KXHCM    1
0040-HALCW    1
0784-GTUUK    1
7979-CORPM    1
2294-DMMUS    1
0872-JCPIB    1
3055-MJDSB    1
9091-WTUUY    1
1618-CFHME    1
3165-HDOEW    1
6581-NQCBA    1
7115-IRDHS    1
8496-DMZUK    1
2040-VZIKE    1
9068-VPWQQ    1
0178-SZBHO    1
0384-RVBPI    1
1689-MRZQR    1
1299-AURJA    1
4525-VZCZG    1
1543-LLLFT    1
5835-BEQEU    1
2788-CJQAQ    1
5565-FILXA    1
0319-QZTCO    1
2120-SMPEX    1
0096-FCPUF    1
0668-OGMHD    1
5552-ZNFSJ    1
2223-KAGMX    1
6507-ZJSUR    1
9408-HRXRK    1
5593-SUAOO    1

C:\Users\sepri\AppData\Local\Temp\ipykernel_8832\1218487619.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(

In [67]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [68]:
df["Churn"].value_counts(normalize=True) * 100

Churn
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [94]:
df[df["TotalCharges"].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [95]:
df.loc[
    df["TotalCharges"].isnull(),
    ["tenure", "MonthlyCharges", "TotalCharges", "Churn"]
]

      tenure  MonthlyCharges  TotalCharges Churn
488        0           52.55           NaN    No
753        0           20.25           NaN    No
936        0           80.85           NaN    No
1082       0           25.75           NaN    No
1340       0           56.05           NaN    No
3331       0           19.85           NaN    No
3826       0           25.35           NaN    No
4380       0           20.00           NaN    No
5218       0           19.70           NaN    No
6670       0           73.35           NaN    No
6754       0           61.90           NaN    No

In [96]:
df.columns.str.strip().tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [97]:
data_types = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "n_unique": df.nunique().values
})

data_types

              column    dtype  n_unique
0         customerID      str      7043
1             gender      str         2
2      SeniorCitizen    int64         2
3            Partner      str         2
4         Dependents      str         2
5             tenure    int64        73
6       PhoneService      str         2
7      MultipleLines      str         3
8    InternetService      str         3
9     OnlineSecurity      str         3
10      OnlineBackup      str         3
11  DeviceProtection      str         3
12       TechSupport      str         3
13       StreamingTV      str         3
14   StreamingMovies      str         3
15          Contract      str         3
16  PaperlessBilling      str         2
17     PaymentMethod      str         4
18    MonthlyCharges  float64      1585
19      TotalCharges  float64      6530
20             Churn      str         2

In [74]:
missing_summary = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percentage": df.isnull().mean() * 100
})

missing_summary = missing_summary[
    missing_summary["missing_count"] > 0
].sort_values(
    "missing_count",
    ascending=False
)

missing_summary

              missing_count  missing_percentage
TotalCharges             11            0.156183

In [13]:
cleand_df = clean_data(df)

In [14]:
cleand_df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [15]:
cleand_df.shape

(7043, 20)

In [17]:
cleand_df.duplicated().sum()

np.int64(22)

In [101]:
cleand_df.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [102]:
assert "customerID" not in cleand_df.columns

In [104]:
assert cleand_df["TotalCharges"].dtype != "object"

In [106]:
assert cleand_df["TotalCharges"].isnull().sum() == 0

In [107]:
assert cleand_df.shape[0] == df.shape[0]

In [108]:
PROCESSED_DATA_PATH = (
    PROJECT_ROOT / "data" / "processed" / "cleaned_telco_customer_churn.csv"
)

In [109]:
cleand_df.to_csv(
    PROCESSED_DATA_PATH,
    index=False
)